### ISSUE TITLE
Should every dset's shape would be ndarray(n,3,3,3)?

### ISSUE THREAD

**Issue by ald2004** [Sapo-Dorado/H5pyLists#1]
Thank you for your work!
and i have same problem while using h5py, but my case is i have 20 h5 files each produce by one 
cpu , then i concat these files into one h5 file by add different dataset.
for example :
bigh5.h5py: contents keys: ['dset0','dset1', ....]
>>> f['dset0']
<HDF5 dataset "dset0": shape (11000,3, 3, 3), type "<f4">
then use your work result is showing below but these 20 items should be 
(10998+11005+11002+11006...and so on):

H5pyList (20 items)
Image (10998, 96, 96, 3),Image (11005, 96, 96, 3),Image (11002, 96, 96, 3),Image (11006, 96, 96, 3),Image (11006, 96, 96, 3)
Path: histo

**Comment by Sapo-Dorado** [comment]
The functions assume that each dataset holds one image, so you would have to split up your datasets into individual images for this code to work.

**Comment by Sapo-Dorado** [comment]
I now realize that having each image in a separate dataset doesn't make sense, so I updated this repository so that it expects all of your images to be in a single dataset within a file. This should help you because all you would have to do is combine your 20 datasets into one rather than split them up into thousands of separate ones.

**Comment by ald2004** [comment]
thank you very much for your replay , it works.
